comments:
  DocumentationOverPrivateProperty:
    active: true
  UndocumentedPublicClass:
    active: true
    excludes: ['**/*.kt']
    includes: ['**/detekt-api/src/main/**/api/*.kt']
  UndocumentedPublicFunction:
    active: true
    excludes: ['**/*.kt']
    includes: ['**/detekt-api/src/main/**/api/*.kt']

complexity:
  StringLiteralDuplication:
    active: true
    excludes: ['**/test/**', '**/*.Test.kt', '**/*.Spec.kt']
    allowedDuplications: 5
    ignoreAnnotation: true
    allowedWithLengthLessThan: 5
    ignoreStringsRegex: '$^'
  ComplexInterface:
    active: true
    allowedDefinitions: 10
    includeStaticDeclarations: false
  CyclomaticComplexMethod:
    active: true
    ignoreSingleWhenExpression: true
  MethodOverloading:
    active: true

exceptions:
  NotImplementedDeclaration:
    active: true
  InstanceOfCheckForException:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: false
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true

naming:
  MemberNameEqualsClassName:
    active: true
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9_]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'

performance:
  ArrayPrimitive:
    active: true

potential-bugs:
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
    excludes: ['**/test/**', '**/*.Test.kt', '**/*.Spec.kt']
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  CollapsibleIfStatements:
    active: true
  EqualsNullCall:
    active: true
  ForbiddenComment:
    active: true
    comments:
      - value: 'TODO:'
      - value: 'FIXME:'
      - value: 'STOPSHIP:'
      - value: '@author'
  FunctionOnlyReturningConstant:
    active: true
  LoopWithTooManyJumpStatements:
    active: true
  MaxLineLength:
    excludes: ['**/test/**', '**/*.Test.kt', '**/*.Spec.kt']
    excludeCommentStatements: true
  MagicNumber:
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreNumbers: ['-1', '0', '1', '2', '100', '1000']
  MayBeConstant:
    active: true
  NestedClassesVisibility:
    active: true
  ProtectedMemberInFinalClass:
    active: true
  UnnecessaryInheritance:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateProperty:
    active: true
    allowedNames: "(_|ignored|expected)"
  UnusedPrivateFunction:
    active: true
  UselessCallOnNotNull:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
